# Generated by Django 5.1.5 on 2025-02-11 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultoria', '0004_pessoa_data_pedido_pessoa_email_pessoa_especialidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='categoria',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='data_pedido',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='morada',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
