# Generated by Django 5.1.5 on 2025-02-11 22:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultoria', '0003_client_profissao_pedido_status_alter_client_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='data_pedido',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoa',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoa',
            name='especialidade',
            field=models.CharField(default='Default Especialidade', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoa',
            name='morada',
            field=models.TextField(default='Default Morada'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoa',
            name='online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='primeiro_nome',
            field=models.CharField(default='Default Morada', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoa',
            name='status',
            field=models.CharField(default='Default Status', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoa',
            name='ultimo_nome',
            field=models.CharField(default='Default ultimo_nome', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='categoria',
            field=models.TextField(),
        ),
    ]
